### ISSUE TITLE
Shouldn't See Tweet Button If It's Not Your Gaming Group

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#153]
https://nerdscorekeeper.azurewebsites.net/PlayedGame/Details/11729 is an example

**Comment by Serneum** [comment]
@jakejgordon How do you get the currently logged-in user? Is [User.Identity](https://github.com/NemeStats/NemeStats/blob/master/Source/UI/Views/Shared/_LoginPartial.cshtml#L13) available on every page because of the header? Does that contain any other user information, like gaming groups? I also see [MVC.Account.UserGamingGroups()](https://github.com/NemeStats/NemeStats/blob/master/Source/UI/Views/Shared/_LoginPartial.cshtml#L15). Is that available on every page?

Notes for myself:
- [Page](https://github.com/NemeStats/NemeStats/blob/master/Source/UI/Views/PlayedGame/Details.cshtml#L53-L54) to update
- [Model](https://github.com/NemeStats/NemeStats/blob/524877f3ccdf1c23c091b6d116603be35c3f3d83/Source/UI/Models/PlayedGame/PlayedGameDetailsViewModel.cs#L30) available to the page above
- [Example](https://github.com/NemeStats/NemeStats/blob/14b4788b6fe93b1a30e9ab7943386c967098a9c7/Source/UI/Views/Account/UserGamingGroups.cshtml#L9-L12) of how to do a foreach in the cshtml file
- Can we get the current user, then get all of the gaming groups, loop over them, and just track if the gaming group was in there? Ex (around [here](https://github.com/NemeStats/NemeStats/blob/master/Source/UI/Views/PlayedGame/Details.cshtml#L53-L54)):
```
var userInGroup = false;
@foreach (var gamingGroup in MVC.Account.UserGamingGroups()) {
    if (gamingGroup.Id == Model.GamingGroupId) {
        userInGroup = true;
        break;
    }
}

@if (userInGroup) {
    <a href="https://twitter.com/share" class="twitter-share-button" data-text="Check out this game I played on &#64;nemestats :" data-size="large" data-related="nemestats" data-count="none" data-hashtags="boardgames" data-dnt="true" title="Tweet a link to this game">Tweet</a>
    <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + '://platform.twitter.com/widgets.js'; fjs.parentNode.insertBefore(js, fjs); } }(document, 'script', 'twitter-wjs');</script>
}
```

**Comment by Serneum** [comment]
Looks like I need to somehow find the ApplicationUser

**Comment by vfportero** [comment]
Is not working as expected.

In that player game of my gaming group (https://nemestats.com/PlayedGame/Details/75659) the tweet button is hidden and i'm logged with the correct player.

Check it out.

**Comment by vfportero** [comment]
Is working well... the problem was with the JS of the tweet button. Closing again
