### ISSUE TITLE
Add pie chart for games played on player details

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#246]
Add a pie chart showing games played with pie slices proportionally sized based on the number of games played

**Comment by mgerdes** [comment]
@jakejgordon Hi Jake. Hope your weekend was good. I'm trying to use the API you have to get back the played games for a particular player. I did find this here, http://docs.nemestats.apiary.io/#reference/gaming-groups/played-games, which gets back all the games for a gaming group, but I couldn't find any way to filter it based on a User Id.

Also, I was able to add nvd3 to the project, and this makes making some pretty cool pie charts really easy, but when looking at the current pie chart on the PlayerDetails page all of the labels for each slice are really crowded together. It's hard to avoid this too because the game names are all of different lengths. It might be best to just remove those labels and rely on the key above and the text that comes up when hovering over a slice. Also it's pretty cool, you can actually click on the text in the key to only show particular slices in the pie chart.

**Comment by jakejgordon** [comment]
Currently you can't filter to a particular player in the API -- but it would be easy to add. I'll create an issue for this and get to work. Also, version 2 of the API is released so you'll want to use this: http://docs.nemestatsapiversion2.apiary.io/#

In regards to the pie chart, I agree. Let's try the legend approach instead of putting the text on the pie slices. MMmmmmm.... pie slices....

**Comment by jakejgordon** [comment]
I forgot to mention (on here) that I did add the ability to filter on player Id on GET /PlayedGames/. You know this because you've already implemented it :)

**Comment by jakejgordon** [comment]
![squished_pie_chart](https://cloud.githubusercontent.com/assets/3045786/10297766/73f71e74-6ba5-11e5-8ee6-23d0cfcbc3df.jpg)

Things are a little squished once you start to get 10+ games. Should have a constant size for the pie chart regardless of the number of games.

**Comment by jakejgordon** [comment]
Mobile is a little squished still (on iPhone devices in particular). See screenshot. 
![iphone_5_pie_chart](https://cloud.githubusercontent.com/assets/3045786/10297860/3630c1fc-6ba6-11e5-80c9-da0176547ecf.jpg)

**Comment by jakejgordon** [comment]
Another enhancement (if it's easy) is to highlight the pie slice when you hover over the legend. Kibana does this which is a nice usability feature. Also, how does this work on touch devices?

We are really close I think!

**Comment by jakejgordon** [comment]
Just a reminder to myself that I need to update apiary documentation to include  the new /PlayerStats/ service once we deploy this.
