### ISSUE TITLE
As a user, i want to limit my gaming group games to 10 to avoid long scroll until last played games

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#337]
In JS and only in desktop, limit the items to 10 and add a toggle button "show all" to expand and show all the items

**Comment by vfportero** [comment]
Maybe it's solved paginating using js script at #296

**Comment by jakejgordon** [comment]
With the BGG geeklist import going into production it is more obvious that we need to address this feature sooner rather than later. Having 500 games renders the page rather useless. Pagination + a type ahead filter on name would probably be the best solution although I'm not sure how much work it is...

**Comment by vfportero** [comment]
The quick solution it's render all and use http://www.listjs.com/ to paginate and search.
The correct and hard way it's to change the API to returns pagination results and implement it on the web.
