### ISSUE TITLE
As a visitor, i want to see 3 main features in the home page to understand better the site

### ISSUE THREAD

**Issue by vfportero** [NemeStats/NemeStats#341]
"Restore" the 3 main features on the home page (bottom of banner) to highlight: 

- Main purpose of the site: Track plays, generate cool stats, gamify the boardgames competitions...
- Integrated with BoardGameGeek
- Free & Open Source: It's free today and always. And OpenSource to catch more contributors

**Comment by vfportero** [comment]
Maybe we can add the BGStats integration as a main feature

**Comment by jakejgordon** [comment]
Here's my first attempt at the main purpose of the site. Will probably have to do a "view more" to see the whole thing -- otherwise it's too big. We could also add an event for when someone clicks "view more" so we know if it's being read. Let me know if you think we should add any pictures or screenshots (since it's a lot of text):

NemeStats (pronounced "Nem-eh-stats") is a completely free, mobile-friendly website for tracking the results of board games. Just <a href='/Account/Register?source=homewidget'>register</a> and you'll automatically have a new Gaming Group created for you. Then set up the Players and Games you want to track, and you are all set to start logging plays!

NemeStats adds a meta layer of fun to your gaming. As you record your games you'll get interesting statistics like number of games played, win/loss percentages, average number of Players per game, longest win streak, etc. You can also earn badges for things like becoming a Champion of a game, becoming someone's Nemesis or Minion, etc. NemeStats also has a <a href='/Home/AboutNemePoints'>NemePoints scoring system</a> which awards Players points based on their rank in the game, the number of Players in the game, as well as the difficulty and duration of the game.

Other features include:
<ul>
  <li>A fully responsive, mobile-friendly website</li>
  <li>Stats by Player, Game, date range, and within Gaming Groups</li>
  <li>The ability to create multiple Gaming Groups (e.g. for home vs. work) and invite other Players to your Gaming Group</li>
  <li>The capability to export all of your plays in case you want to do your own stats</li>
  <li>A full-featured <a href='http://docs.nemestatsapiversion2.apiary.io/'>REST API documented on Apiary.io</a> in case you are interested in pulling data from or pushing data to NemeStats yourself.</li>
  <li><a href='http://boardgamegeek.com/'>BoardGameGeek</a> integration</li>
  <li><a href='https://www.bgstatsapp.com/'>Board Game Stats</a> integration</li>
</ul>

**Comment by jakejgordon** [comment]
Here's an attempt at the BoardGameGeek / Board Game Stats integration piece. Attached are 2 images that might come in handy for the BG Stats piece.

BoardGameGeek Integration

If you already have an account with BoardGameGeek you can import your existing geek list directly into the site to get started quickly. BoardGameGeek has also graciously allowed us to display images of board games, search for board games to add to your gaming Group, and it also provides some basic statistics about games which we include in our points calculation.

Board Game Stats iOS App Integration

Need a better mobile experience? Board Game Stats is the premier iOS app for recording the results of board games. It now comes with the ability to synchronize your NemeStats Players and Game Definitions so getting started is a breeze. You can also push your plays from the app directly back into NemeStats!

You can <a href='https://itunes.apple.com/us/app/board-game-stats/id892542000'>download Board Game Stats</a> from the app store. Simply configure your NemeStats credentials from the main settings screen and the rest should be intuitive.
![app_store_download](https://cloud.githubusercontent.com/assets/3045786/14578397/4282f10e-0355-11e6-90f6-f711540c6aff.png)
![bgstats](https://cloud.githubusercontent.com/assets/3045786/14578398/4285e8be-0355-11e6-9a3e-865940a64f2d.png)

**Comment by jakejgordon** [comment]
Last part:

Free and Open Source Forever

NemeStats will always be Open Source, no cost, and completely ad-free! We built NemeStats because we love board games and want to provide a fun experience for other gamers. Please share your feedback with us via <a href='http://nemestats.idea.informer.com/'>Idea Informer</a>, <a href='mailto:nemestats@gmail.com'>email</a>, or <a href='https://nemestats-slack-invitation.herokuapp.com/'>join our Slack channel</a> to join in the discussion.

In addition to feedback, we are always looking for new contributors -- especially if you are a developer, UX designer, or have marketing skills. You can find our <a href='https://github.com/NemeStats/NemeStats'>GitHub repository here</a>.

**Comment by jakejgordon** [comment]
Here is attempt #2 which has both the bulleted list and the longer text. Let me know what you think (or feel free to make changes as you see fit):

1 - NemeStats lets you...
* Track the results of board game plays
* Record from your mobile phone
* Generate interesting statistics
* Create multiple Gaming Groups
* Earn Achievements and Badges
* Export your data

NemeStats (pronounced "Nem-eh-stats") is a completely free, mobile-friendly website for tracking the results of board games. Just register and you'll automatically have a new Gaming Group created for you. Then set up the Players and Games you want to track, and you are all set to start logging plays!

NemeStats adds a meta layer of fun to your gaming. As you record your games you'll get interesting statistics like number of games played, win/loss percentages, average number of Players per game, longest win streak, etc. You can also earn badges for things like becoming a Champion of a game, becoming someone's Nemesis or Minion, etc. NemeStats also has a NemePoints scoring system which awards Players points based on their rank in the game, the number of Players in the game, as well as the difficulty and duration of the game.

Other features include:

* A fully responsive, mobile-friendly website
* Stats by Player, Game, date range, and within Gaming Groups
* The ability to create multiple Gaming Groups (e.g. for home vs. work) and invite other Players to your Gaming Group
* The capability to export all of your plays in case you want to do your own stats
* A <a href='http://docs.nemestatsapiversion2.apiary.io/'>full-featured REST API documented on Apiary.io</a> in case you are interested in pulling data from or pushing data to NemeStats yourself.


2 - NemeStats is enhanced with...
* <a href='https://www.bgstatsapp.com/'>Board Game Stats</a> on iOS
* BoardGameGeek integration

BoardGameGeek Integration

If you already have an account with BoardGameGeek you can import your existing geek list directly into the site to get started quickly. BoardGameGeek has also graciously allowed us to display images of board games, search for board games to add to your gaming Group, and it also provides some basic statistics about games which we include in our points calculation.

Board Game Stats iOS App Integration

Need a better mobile experience? Board Game Stats is the premier iOS app for recording the results of board games. It now comes with the ability to synchronize your NemeStats Players and Game Definitions so getting started is a breeze. You can also push your plays from the app directly back into NemeStats!

You can <a href='https://itunes.apple.com/us/app/board-game-stats/id892542000'>download Board Game Stats from the app store</a>. Simply configure your NemeStats credentials from the main settings screen and the rest should be intuitive.

3 - NemeStats is will always be...
* Completely free
* Without advertisements
* Open source and <a href='https://github.com/NemeStats/NemeStats'>on GitHub</a>
* Actively developed on
* Looking for contributors

Free and Open Source Forever

NemeStats will always be Open Source, no cost, and completely ad-free! We built NemeStats because we love board games and want to provide a fun experience for other gamers. Please share your feedback with us via <a href='http://nemestats.idea.informer.com/proj/?mod=one'>Idea Informer</a>, <a href='mailto:nemestats@gmail.com'>email</a>, or <a href='https://nemestats-slack-invitation.herokuapp.com/'>join our Slack channel</a> to join in the discussion.

In addition to feedback, we are always looking for new contributors -- especially if you are a developer, UX designer, or have marketing skills. You can <a href='https://github.com/NemeStats/NemeStats'>find our GitHub repository here</a>.
