### ISSUE TITLE
Add support for dynamic achievements

### ISSUE THREAD

**Issue by jakejgordon** [NemeStats/NemeStats#376]
Build a system for awarding achievements that doesn't require code to be deployed every time there is a new achievement.

**Comment by jakejgordon** [comment]
I think the back-end is working in a database-driven format. @vfportero has mentioned that he doesn't support the approach but hasn't shared any details yet. I'm halting further development on this until we can come to some kind of agreement. Victor, can you articulate your concerns with the approach and describe the alternative solution? I think the main advantage of this approach is that we could deploy new achievements simply via the database. This means we wouldn't even have to do a deployment to get new achievements out there. The biggest downside is lack of scalability. As it's implemented right now, after each game, every player will have every single achievement re-evaluated. This would be better off in an asynchronous queue or nightly/hourly batch job.

**Comment by vfportero** [comment]
I don't like the database driven approach because its hardly testable, rigid (you can only calculate achievements with db data) and non scalable.

My proposal it's move this logic to the business logic layer and create a service which calculate the badge earning.

My code speaks better than me... let me make a branch to demostrate my approach before take the final decission :)
