### ISSUE TITLE
Changing password results in 500 response.

### ISSUE THREAD

**Issue by toddfast** [NemeStats/NemeStats#729]
Trying to change my password results in an HTTP 500 response from the `POST` to `https://nemestats.com/Account/ChangePassword`.  I don't see any particularly useful debug information in the console, just the HTML error page response.

FWIW, I was able to change my email address just fine, but I've recently been having trouble posting plays as well (more 500s). I don't know if this is something site-wide or just for me (username `glax`).

**Comment by HolisticDeveloper** [comment]
I've recently taken over as the maintainer for NemeStats and I'm going back through the older issues. I know the site was running into some issues last year due to a lack of disk space for the database. I'm closing this issue for now because I don't have the error logs from that time period, but if you're still seeing this issue please let me know.
